# Site wide configuration

title:            World Leelavivat
locale:           en_US
url:              //world.leelavivat.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: World Leelavivat
  avatar: bio-photo.png
  bio: "Developer. Industrial Engineer. Photographer."
  email: w.leelavivat@gmail.com
  disqus-shortname: wleelavivat
  twitter: wleelavivat
  facebook: #username
  google:
    plus: WorldLeelavivat
    analytics: UA-56743469-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: wleelavivat
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: wleelavivat
  instagram: wleelavivat
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
