# Site wide configuration

title:            World Leelavivat
locale:           en_US
url:              http://world.leelavivat.com
url:              http://wleelavivat.github.io/wleelavivat
url:              http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: World Leelavivat
  avatar: bio-photo.jpg
  bio: "Describe your self."
  email: w.leelavivat@gmail.coom
  disqus-shortname:
  twitter: wleelavivat
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: wleelavivat
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: wleelavivat
  instagram: wleelavivat
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
